### ISSUE TITLE
Ensure Empty Lines before Headings/after Title

### ISSUE THREAD

**Issue by fwilhe** [Mogztter/asciidoc-googledocs-addon#10]
When I convert a Document that uses the google docs formatting for title/headings, the created AsciiDoc is not what I would expect.

Generated AsciiDoc:

```
= Title
== Heading Level 1
Some Text

=== Heading Level 2
Some Text
```

There needs to be an empty line before `Heading Level 1`. The generated code leads to the "Level 1"-block is completely missing.

I would go so far to say, it would be better to have an empty line also after the title and headings.

So my expectation for the output is:

```
= Title

== Heading Level 1

Some Text

=== Heading Level 2

Some Text
```

**Comment by Mogztter** [comment]
Hello @fwilhe, I think this is a one line fix here to append a new line: https://github.com/Mogztter/asciidoc-googledocs-addon/blob/master/app/Code.gs#L221

**Comment by fwilhe** [comment]
Hi @Mogztter, thanks for the hint. I knew this would be a trivial change, but I did not find the time to get into how to run/test this code. If I have that time, I'll open a PR.

**Comment by fwilhe** [comment]
So, I've copied the code to a google script project, started that with my demo document, started the conversion, but it just takes forever (I only see the spinning wheel). Not sure what the problem is, made the PR anyway, since it is really trivial.

I would appreciate hints on how to run this thing (see #11), and I'm willing to contribute this when it works for me.

**Comment by Mogztter** [comment]
To be honest I don't remember exactlly how I set up my development environment :wink: 
But basically I've followed the Quickstart from Google then iterate on my addon/script: https://developers.google.com/apps-script/quickstart/docs

**Comment by Mogztter** [comment]
Looking more closely at this issue I think we should only add an extra empty line after the document title when there's no paragraph (ie. a document title followed by a level 1 title)

**Comment by Mogztter** [comment]
To keep the code simple we could just add an extra empty line after the document title no matter what the next line is

**Comment by Mogztter** [comment]
@fwilhe Did you create two files `Code.gs` and `Dialog.html` ?

![asciidoc](https://cloud.githubusercontent.com/assets/333276/14227669/3338aaf6-f903-11e5-8130-95e25c8295fb.PNG)

**Comment by fwilhe** [comment]
Yes, exactly that. It seems one can only copy/paste to get the content in, at least that is what I did, and I can run the addon, it just does not finish in a reasonable amount of time.

**Comment by Mogztter** [comment]
I did the same and it's working... very strange!
Do you have any log in "Execution Script" ?

**Comment by fwilhe** [comment]
Yes, I have: https://gist.github.com/fwilhe/c652d88cf51eb1fe9922c095e31cf7f9

**Comment by Mogztter** [comment]
Interesting, after the following line you should have a result. I don't know why this isn't working:

`[16-04-04 19:43:14:713 CEST] Execution succeeded [0.162 seconds total runtime]`

Could you please take screenshots or a capture your screen, so I can see exactly the different steps ?
