### ISSUE TITLE
Document how to run the code for development

### ISSUE THREAD

**Issue by fwilhe** [Mogztter/asciidoc-googledocs-addon#11]
I would be great to add some hints to the readme about how the code can be run. This would lower the barrier for potential contributes who never before worked with a googledocs plugin.

**Comment by Mogztter** [comment]
Definitively! I didn't take the time to do it but I will try to find some time.

**Comment by Mogztter** [comment]
I think @briandominick documentation fixes this issue ? @fwilhe do you agree ?

**Comment by fwilhe** [comment]
I don't have time to test it now, but it looks good to me. Thanks.
