### ISSUE TITLE
Converting forever

### ISSUE THREAD

**Issue by Kabhal** [Mogztter/asciidoc-googledocs-addon#13]
Hi,

The extension is converting forever (any doc, any mode : convert all or convert selection).
Chrome Versions :
- 51.0.2704.79 (64-bit)
- 51.0.2704.106 (64-bit)

OS : Linux

An idea ?

**Comment by Mogztter** [comment]
Hello @Kabhal, any errors when dev tools are enabled ? Could you please share one of your document so I can try to reproduce this issue ?
Thanks.

**Comment by Kabhal** [comment]
You can reproduce with a new doc containing one word.
Anyway I have an error in the console :

[docs.google.com-1467040003146.log.zip](https://github.com/Mogztter/asciidoc-googledocs-addon/files/335153/docs.google.com-1467040003146.log.zip)

**Comment by Mogztter** [comment]
Yes you're right, but this is a bit strange since the addon is/was working for me :meh:

**Comment by Mogztter** [comment]
And `rows` variable seems to be undefined...

**Comment by Mogztter** [comment]
@Kabhal I've published a new version to remove this line of code. Version 11 should be available soon, could you please retest with this version ?

**Comment by briandominick** [comment]
After unfortunately reproducing this bug, I just tested V11, and it works! And it's a nice start -- better than most tools I've tried! I'm going to contribute basic testing instructions, and if this is close enough to what I need, I might add some functionality. Thanks!

**Comment by Kabhal** [comment]
How did you test v11 ? my Chrome does not propose this version, sticking to 10 :/

**Comment by Mogztter** [comment]
I don't know why but version 11 is still in "preliminary state" on the Chrome Web Store developer dashboard.

I will contact Google's support to find out.

Could you try to reinstall the add-on from the Chrome Web Store?

**Comment by Kabhal** [comment]
this is reinstalling v10

**Comment by Mogztter** [comment]
I've checked "publish on Marketplace" which requires extra steps. I've published again a new version (version 12) and this version is now in "review". This version should be available in the next few days.
The next version (version 13) will include #15 :smile:

**Comment by Mogztter** [comment]
> Hello,
Thanks for your submission.  Your add-on has been reviewed and is now approved for public use!
AsciiDoc Processor will now appear in the Google Docs Add-ons store.  Please email us back if you have any questions or comments moving forward.
Congrats and good luck!
Sincerely,
The Google Docs Add-ons Team

Version 12 should now be available. @Kabhal could you please give it a try ?

**Comment by Kabhal** [comment]
v12 is working thanks !
