### ISSUE TITLE
Not verified by Google error.

### ISSUE THREAD

**Issue by RobertNL** [Mogztter/asciidoc-googledocs-addon#34]
Google no longer allows this App. Now get the following error whenever I try to install the App:
"Sign in with Google temporarily disabled for this app
This app has not been verified yet by Google in order to use Google Sign In."

**Comment by Mogztter** [comment]
Hello Robert and thanks for the heads up.
I will have a look... 👀

**Comment by Mogztter** [comment]
The migration guide from Google is really confusing... I've published the application again and I'm waiting Google's approval. I will let you know when they come back me 😀

**Comment by RobertNL** [comment]
Thanks!

**Comment by RobertNL** [comment]
Any update?

**Comment by Mogztter** [comment]
I've received an email from Google, they are doing a review (again).
Hopefully it won't take long and the add-on will soon be available.

**Comment by Mogztter** [comment]
@RobertNL After much back and forth, the add-on should be available (and verified by Google). Could you please confirm that it's effectively the case ?

**Comment by RobertNL** [comment]
Still getting same error. 
"Sign in with Google temporarily disabled for this app
This app has not been verified yet by Google in order to use Google Sign In."
I tried downloading another Docs add-in and it worked fine.
I'd still like to get this tool!

**Comment by Mogztter** [comment]
I found something in the Google Cloud console... I will send a request to get verified.

**Comment by bharath-elastic** [comment]
it seems to be a really nice use case. wish you could get Google to verify this app so we can use it.

**Comment by Mogztter** [comment]
I think it's now mandatory to provide a web page with the general terms and conditions and probably the privacy policies.

I will try to setup a simple page this week or next week 😉

**Comment by RobertNL** [comment]
Thanks! Love to try this out.

*Robert Thomas*
Innovation Program
Open Geospatial Consortium
Ph: +1 709 728 0434

The OGC: Making *Location* Count...
www.opengeospatial.org

**Comment by Mogztter** [comment]
After a dozen email exchanges the add-on is now verified :tada: :tada: :tada: 
You will need to signin with your Google account and then Allow the add-on to read your Google Docs document:

![select-account](https://user-images.githubusercontent.com/333276/64918874-72138100-d7a4-11e9-9fac-ac8b90aa18b7.png)

![aouth](https://user-images.githubusercontent.com/333276/64918876-7475db00-d7a4-11e9-8aff-c5c8c29c70a1.png)


Let me know if it works for you.

**Comment by fviolette** [comment]
Excellent news :+1: Will be so much easier to incorporate casual contributions and early drafts now!

**Comment by ggrossetie** [comment]
I'm closing this issue as I think everything is working fine now.
