### ISSUE TITLE
AsciiDoc no longer shows up in Add-on menu

### ISSUE THREAD

**Issue by knylander** [Mogztter/asciidoc-googledocs-addon#36]
AsciiDoc Processor no longer appears in the Add-on menu nor in list of extensions available to install for Google Docs. 

To reproduce: 
. Open a new Google doc. 
. Click Add-ons. 

No AsciiDoc Processor option. 
Selecting Manage Add-ons opens the GSuite Marketplace. 
Searching the market place for AsciiDoc keyword returns no results. 

The [procedure](https://github.com/Mogztter/asciidoc-googledocs-addon) with the install link to the [Chrome Web Store](https://chrome.google.com/webstore/detail/asciidoc-processor/eghlmnhjljbjodpeehjjcgfcjegcfbhk) returns a 404. 

When I go to my Google account's security page and check Third-party access, the AsciiDoc Processor options match the ones listed in https://github.com/Mogztter/asciidoc-googledocs-addon/issues/34. 

Is anyone else having this issue?

**Comment by Mogztter** [comment]
Thanks for the heads-up 👍 
Google changed the publish procedure and now it's a nightmare! It was straightforward and easy and now it's just very confusing... 
I will try to ping them again but for now the application is "Unpublished" and I can't click the "Publish" button... even though every (no optional) fields are filled 😞

**Comment by knylander** [comment]
:(  It seemed strange that they changed from the Google Chrome Store to the GSuite Marketplace. It's like you have to have the processor listed on two different places. 
I've lost a few other add-ons as well. Only one is now present and I had several installed.

**Comment by fviolette** [comment]
Bad news! And way to discourage contributions.
Hoping for a turnaround somehow 🤞

**Comment by Mogztter** [comment]
I've contacted the support and the extension is now available again 🎉

- https://gsuite.google.com/marketplace/search/asciidoc
- https://gsuite.google.com/marketplace/app/asciidoc_processor/1023004302050

**Comment by knylander** [comment]
Excellent news! Thank you!

**Comment by ggrossetie** [comment]
I've updated the README in https://github.com/Mogztter/asciidoc-googledocs-addon/commit/b70259eea794eb0254741c08ed90cab42ea02eef and as mentioned earlier the extension is now available again on the Google Workspace Marketplace: https://gsuite.google.com/marketplace/app/asciidoc_processor/1023004302050
