### ISSUE TITLE
limit permissions

### ISSUE THREAD

**Issue by evbacher** [Mogztter/asciidoc-googledocs-addon#37]
Can you add this to the top of addon.gs so that you only need permission to access the current document?

```
/**
 * @OnlyCurrentDoc  Limits the script to only accessing the current document.
 */
```

**Comment by Mogztter** [comment]
Hello Ed!
Sure it sounds like an excellent idea. Thanks for the hint, I wasn't aware of this special comment to limit permissions 👍
