### ISSUE TITLE
Authorization is required

### ISSUE THREAD

**Issue by ddieruf** [Mogztter/asciidoc-googledocs-addon#45]
Logged in to docs with my company google account, I've done the suggested installation of the add-on. I granted all requested permission while installing the add-on, but when I go to convert I get the following error.

![image](https://user-images.githubusercontent.com/16946028/199736334-4a25abbc-bc98-4b12-bdf2-5106b6ad4828.png)

I am the owner of the document and I tried "share" to "anyone with the link" as a viewer, commenter, and editor. All configurations given me the same error message.

**Comment by ggrossetie** [comment]
Hmmm 🤔 
Could you please share the document with me? I sent you an email.

**Comment by ddieruf** [comment]
Shared

**Comment by ggrossetie** [comment]
![image](https://user-images.githubusercontent.com/333276/199829732-28ad20d7-3f7f-4b8a-812e-f017a3e99f48.png)

**Comment by ggrossetie** [comment]
It's working on my side, it might be a special authorization that you need to enable on the Google company account, not sure... 🤔

**Comment by ddieruf** [comment]
Interesting. If I share the doc as "anyone with the link" and open it in incognito I am able to convert. So I guess that confirms your theory.

**Comment by ddieruf** [comment]
@Mogztter a thought just occurred to me. I also using the [code-blocks add-on](https://github.com/alexwforsythe/code-blocks) in the same document with no issue. Is it worth investigating why that add-on is able to convert text and the asciidocs add-on can't?

If we trace this issue back to settings/permissions in the Google company account, what is different between the two add-ons?

**Comment by ggrossetie** [comment]
> If we trace this issue back to settings/permissions in the Google company account, what is different between the two add-ons?

Not sure, maybe "Code Blocks" is explicitly authorized? It's interesting to note that the AsciiDoc Processor Add-on requires less authorizations than "Code Blocks".

![image](https://user-images.githubusercontent.com/333276/201172177-21784d2f-75bc-4578-b74d-62856b3692c1.png)

https://workspace.google.com/marketplace/app/asciidoc_processor/1023004302050


In "Installation Settings" both "Individual" and "Admin Install" are enabled. In your case, I think you need to install the add-on on your domain:

![image](https://user-images.githubusercontent.com/333276/201175054-b4b7adad-de30-4753-865f-08ce17b284d6.png)

**Comment by ddieruf** [comment]
I'll go back and see what add-ons have been internally approved. Thank you.

**Comment by ggrossetie** [comment]
Found this explanation on the web:

> If you received the message: "ScriptError: Authorization is required to perform that action" here is the most probable cause and solution.
>
> Typically is the case that when a user received this notification it's because they are currently logged in with more than one Google Account. 
>
> This is a security procedure from Google, the way to solve this is by installing the addon in all of your Google accounts.

@ddieruf Does it apply to you?

**Comment by ggrossetie** [comment]
Might solve your issue: https://www.2hac.com/faq/authorization-is-required-to-perform-that-action/

**Comment by ddieruf** [comment]
I am using chrome with my personal account but logged in to gsuite with my company account. So, yes this might.

**Comment by ddieruf** [comment]
Thx for the help. I'll try it out.

**Comment by ggrossetie** [comment]
Let me know if it worked. I might be able to catch this error and print a useful error message to indicate how to workaround/resolve this issue.

**Comment by ddieruf** [comment]
I went through the steps and my account was already set up the way that was suggested. So no real movement.
